[versions]

kotlin = "2.3.0"
jackson = "2.19.2"
shadow = "9.3.1"
velocity = "3.5.0-SNAPSHOT"

[libraries]

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow-jar = { id = "com.gradleup.shadow", version.ref = "shadow" }
